# Generated by Django 4.2.9 on 2024-01-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_pimage_alter_follow_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimage',
            field=models.ImageField(default='pimage/userprofile_default', upload_to='pimages/'),
        ),
    ]
