# Generated by Django 4.2.9 on 2024-01-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_user_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pimage',
            field=models.ImageField(default='pimages/defaultimage/userprofile_default.jpeg', upload_to='pimages/'),
        ),
    ]
